# @generated by `cargo buckal`

load("@prelude//:prelude.bzl", "native")
load("@prelude//rust:cargo_package.bzl", "apply_platform_attrs", "cargo")
load("@prelude//utils:selects.bzl", "selects")
load("@buckal//:cargo_buildscript.bzl", __buildscript_run__="buildscript_run")

def _set_profile_flag(**kwargs):
    rustc_flags = kwargs.get("rustc_flags", []) + select({
        "buckal//config/mode:debug": ["-Copt-level=0"],
        "buckal//config/mode:release": ["-Copt-level=3"],
        "DEFAULT": [],
    })
    return rustc_flags

def _patch_buildscript_env(**kwargs):
    env = kwargs.get("env", {})
    env.update(OPT_LEVEL=select({
        "buckal//config/mode:debug": "0",
        "buckal//config/mode:release": "3",
        "DEFAULT": "0",
    }))
    env.update(DEBUG=select({
        "buckal//config/mode:debug": "1",
        "buckal//config/mode:release": "0",
        "DEFAULT": "1",
    }))
    env.update(PROFILE=select({
        "buckal//config/mode:debug": "debug",
        "buckal//config/mode:release": "release",
        "DEFAULT": "debug",
    }))
    return env

def rust_binary(name, **kwargs):
    deps = kwargs.pop("deps", [])
    os_deps = kwargs.pop("os_deps", {})
    named_deps = kwargs.pop("named_deps", {})
    os_named_deps = kwargs.pop("os_named_deps", {})
    deps = _merge_os_deps(deps, os_deps)
    named_deps = _merge_os_named_deps(named_deps, os_named_deps)
    kwargs.update(deps = deps, named_deps = named_deps)
    # Set the crate name in the environment
    crate_name = kwargs.get("crate")
    env = kwargs.get("env", {})
    env.update(CARGO_CRATE_NAME=crate_name)
    kwargs.update(env=env)
    # Set build profile flags
    rustc_flags = _set_profile_flag(**kwargs)
    kwargs.update(rustc_flags=rustc_flags)
    cargo.rust_binary(name = name, **kwargs)

def rust_library(name, **kwargs):
    deps = kwargs.pop("deps", [])
    os_deps = kwargs.pop("os_deps", {})
    named_deps = kwargs.pop("named_deps", {})
    os_named_deps = kwargs.pop("os_named_deps", {})
    deps = _merge_os_deps(deps, os_deps)
    named_deps = _merge_os_named_deps(named_deps, os_named_deps)
    kwargs.update(deps = deps, named_deps = named_deps)
    # Set the crate name in the environment
    crate_name = kwargs.get("crate")
    env = kwargs.get("env", {})
    env.update(CARGO_CRATE_NAME=crate_name)
    kwargs.update(env=env)
    # Set build profile flags
    rustc_flags = _set_profile_flag(**kwargs)
    kwargs.update(rustc_flags=rustc_flags)
    cargo.rust_library(name = name, **kwargs)

def rust_test(name, **kwargs):
    deps = kwargs.pop("deps", [])
    os_deps = kwargs.pop("os_deps", {})
    named_deps = kwargs.pop("named_deps", {})
    os_named_deps = kwargs.pop("os_named_deps", {})
    deps = _merge_os_deps(deps, os_deps)
    named_deps = _merge_os_named_deps(named_deps, os_named_deps)
    kwargs.update(deps = deps, named_deps = named_deps)
    # Set the crate name in the environment
    crate_name = kwargs.get("crate")
    env = kwargs.get("env", {})
    env.update(CARGO_CRATE_NAME=crate_name)
    kwargs.update(env=env)
    platform = kwargs.pop("platform", {})
    kwargs = apply_platform_attrs(platform, kwargs)
    # Set build profile flags
    rustc_flags = _set_profile_flag(**kwargs)
    kwargs.update(rustc_flags=rustc_flags)
    native.rust_test(name = name, **kwargs)

def buildscript_run(name, **kwargs):
    # Patch build script environment
    env = kwargs.get("env", {})
    env = _patch_buildscript_env(env=env)
    kwargs.update(env=env)
    __buildscript_run__(name = name, **kwargs)

def _merge_os_deps(default_deps, os_deps):
    if not os_deps:
        return default_deps

    def merge(base):
        base_list = list(base)
        select_map = {"DEFAULT": base_list}
        for key in sorted(os_deps):
            select_map[_platform_label(key)] = _branch_deps(base_list, os_deps, key)
        return select(select_map)

    return selects.apply(default_deps, merge)

def _branch_deps(base_list, os_deps, key):
    def concat(*extras):
        merged = list(base_list)
        for extra in extras:
            merged = merged + list(extra)
        return merged

    return selects.apply_n(_inherited_keys(os_deps, key), concat)

def _inherited_keys(os_deps, key):
    """The os_deps values a `key` branch must contribute, least-specific first.

    Buck2 picks exactly one select branch — it does not union the branches that
    match. So a refined branch has to carry the OS-level deps too, or a crate
    with both a `cfg(unix)` dep and a `cfg(all(aarch64, linux))` dep would lose
    the former on linux-arm64.
    """
    os_key = _os_of(key)
    if key != os_key and os_key in os_deps:
        return [os_deps[os_key], os_deps[key]]
    return [os_deps[key]]

def _merge_os_named_deps(default_named, os_named_deps):
    # os_named_deps is alias-first: {"alias": {"linux": "//:dep", "linux-arm64": "//:dep"}}.
    if not os_named_deps:
        return default_named

    def merge(base):
        base_dict = dict(base)
        keys = set()
        for per_os in os_named_deps.values():
            keys.update(per_os.keys())

        def named_for(key):
            merged = base_dict
            for alias, per_os in os_named_deps.items():
                # Same inheritance as _inherited_keys: a refined branch takes the
                # alias's OS-level target unless the alias overrides it for this
                # exact platform.
                value = per_os.get(key, per_os.get(_os_of(key)))
                if value != None:
                    merged = _set_named_dep(merged, alias, value)
            return merged

        select_map = {"DEFAULT": base_dict}
        for key in sorted(keys):
            select_map[_platform_label(key)] = named_for(key)

        return select(select_map)

    return selects.apply(default_named, merge)

def _set_named_dep(named, alias, value):
    def set_alias(curr, target):
        merged = dict(curr)
        merged[alias] = target
        return merged

    return selects.apply_n([named, value], set_alias)

# A platform key is either an OS name (`linux`) or an OS/CPU pair
# (`linux-arm64`). buckal emits the bare OS key when a dependency applies to
# every supported CPU of that OS, and the refined key when it does not — e.g.
# `cpufeatures` needs `libc` only on aarch64 Linux, which an OS-keyed map cannot
# express at all.
_OS_LABELS = {
    "linux": "prelude//os/constraints:linux",
    "macos": "prelude//os/constraints:macos",
    "windows": "prelude//os/constraints:windows",
}

_PLATFORM_LABELS = {
    "linux-arm64": "buckal//platforms:linux-arm64",
    "linux-x86_64": "buckal//platforms:linux-x86_64",
    "macos-arm64": "buckal//platforms:macos-arm64",
    "macos-x86_64": "buckal//platforms:macos-x86_64",
    "windows-arm64": "buckal//platforms:windows-arm64",
    "windows-x86_64": "buckal//platforms:windows-x86_64",
}

def _os_of(key):
    # CPU names contain `_` (`x86_64`) but never `-`, so the first `-` is the
    # OS/CPU boundary.
    return key.split("-")[0]

def _platform_label(key):
    # Both an OS key and a refined key can match the same platform; Buck2 resolves
    # that by refinement, preferring the config_setting whose constraints are a
    # strict superset. That is why the refined branch must be complete — see
    # _inherited_keys.
    if key in _OS_LABELS:
        return _OS_LABELS[key]
    if key in _PLATFORM_LABELS:
        return _PLATFORM_LABELS[key]
    fail("Unsupported platform key %s. Expected one of: %s" % (
        key,
        ", ".join(sorted(_OS_LABELS.keys() + _PLATFORM_LABELS.keys())),
    ))
